name: Sync Latest YouTube Morphe APK

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Download latest YouTube APK
        run: |
          set -e

          mkdir -p temp
          cd temp

          curl -L -o release.json \
          https://api.github.com/repos/RookieEnough/Morphe-AutoBuilds/releases/latest

          APK_URL=$(grep browser_download_url release.json | grep youtube-universal-morphe | grep '\.apk' | cut -d '"' -f 4 | head -n 1)

          if [ -z "$APK_URL" ]; then
            echo "APK not found"
            exit 1
          fi

          APK_NAME=$(basename "$APK_URL")

          echo "Downloading:"
          echo "$APK_NAME"

          wget "$APK_URL"

          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV

      - name: Delete previous release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest --yes || true

      - name: Delete previous tag
        run: |
          git push origin --delete latest || true

      - name: Create release with original filename
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create latest \
          temp/"$APK_NAME" \
          --title "$APK_NAME" \
          --notes "Latest synced YouTube Morphe APK"
