name: Sync Latest YouTube Morphe APK

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Download latest release APK
        shell: bash
        run: |
          set -e

          mkdir -p temp
          cd temp

          echo "Getting latest release JSON..."

          curl -L -o release.json \
          https://api.github.com/repos/RookieEnough/Morphe-AutoBuilds/releases/latest

          echo "Searching for YouTube APK..."

          APK_URL=$(cat release.json | grep browser_download_url | grep youtube-universal-morphe | grep '\.apk' | cut -d '"' -f 4 | head -n 1)

          if [ -z "$APK_URL" ]; then
            echo "ERROR: APK URL not found"
            cat release.json
            exit 1
          fi

          echo "Found APK:"
          echo "$APK_URL"

          wget -O youtube-morphe-latest.apk "$APK_URL"

      - name: Remove old APKs
        run: rm -f *.apk

      - name: Move new APK
        run: mv temp/youtube-morphe-latest.apk ./

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add youtube-morphe-latest.apk

          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "Update latest YouTube Morphe APK"

          git push
